import type { AuditLog, Initiative, Owner } from '../types';

const today = new Date();
const daysAgo = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

export const seedOwners: Owner[] = [
  { id: 'own-1', name: 'Sarah Al-Mansoori' },
  { id: 'own-2', name: 'Ahmed Karim' },
  { id: 'own-3', name: 'Priya Natarajan' },
  { id: 'own-4', name: 'David Okonkwo' },
  { id: 'own-5', name: 'Lina Hassan' },
  { id: 'own-6', name: 'Marco Silva' },
];

export const seedInitiatives: Initiative[] = [
  {
    id: 'INIT-1001',
    category: 'AIs',
    name: 'Predictive Grid Demand Engine',
    description:
      'AI-driven forecasting to anticipate grid demand during peak summer months across the city.',
    owner: 'Sarah Al-Mansoori',
    currentProcess:
      'Manual demand projections built in spreadsheets, reviewed weekly by operations leads.',
    enhancedProcess:
      'Automated ML pipeline producing hourly demand forecasts with confidence bands surfaced in an ops dashboard.',
    budget: '$2.4M',
    demandNumber: 'DEM-901',
    status: 'Active',
    urgency: 'High',
    comments: 'Pilot running in District 3 before full rollout.',
    implementer: 'Accenture',
    logDate: daysAgo(1),
    logDescription: 'Model v2 deployed to staging. Accuracy +6.2% vs baseline.',
    severity: 'Low',
    updatedAt: daysAgo(1),
  },
  {
    id: 'INIT-1002',
    category: 'Enhancements',
    name: 'Customer Billing Portal Refresh',
    description:
      'Rework the self-service billing portal to reduce call-centre volume and improve NPS.',
    owner: 'Ahmed Karim',
    currentProcess: 'Legacy portal built on an old CMS; limited mobile responsiveness.',
    enhancedProcess: 'Responsive SPA with unified auth and instant invoice download.',
    budget: '$780K',
    demandNumber: 'DEM-905',
    status: 'Pending',
    urgency: 'Medium',
    comments: 'Awaiting legal review of revised T&Cs.',
    implementer: 'Internal',
    logDate: daysAgo(3),
    logDescription: 'Blocked on legal review. Escalated to head of compliance.',
    severity: 'Medium',
    updatedAt: daysAgo(3),
  },
  {
    id: 'INIT-1003',
    category: 'Projects',
    name: 'Solar Rooftop Program Expansion',
    description:
      'Extend the rooftop solar programme to industrial customers with on-site storage.',
    owner: 'Priya Natarajan',
    currentProcess: 'Residential rollout live; no industrial offering yet.',
    enhancedProcess:
      'New pricing tier, installer network, and storage financing for industrial sites.',
    budget: '$12.0M',
    demandNumber: 'DEM-912',
    status: 'Active',
    urgency: 'High',
    comments: '',
    implementer: 'IBM + Local EPC',
    logDate: daysAgo(5),
    logDescription: '4 industrial pilots signed for Q3 installation.',
    severity: 'Low',
    updatedAt: daysAgo(5),
  },
  {
    id: 'INIT-1004',
    category: 'Licenses',
    name: 'Oracle EBS License Consolidation',
    description: 'Consolidate ERP licenses to reduce annual spend.',
    owner: 'David Okonkwo',
    currentProcess: 'Five separate agreements across business units.',
    enhancedProcess: 'Single enterprise agreement with true-down clause.',
    budget: '$1.1M saving',
    demandNumber: 'DEM-915',
    status: 'Completed',
    urgency: 'Medium',
    comments: 'Signed off by CFO.',
    implementer: 'Deloitte',
    logDate: daysAgo(20),
    logDescription: 'Contract executed. $1.1M annualised saving validated.',
    severity: 'Low',
    updatedAt: daysAgo(20),
  },
  {
    id: 'INIT-1005',
    category: 'Services',
    name: 'Field Ops Mobile Dispatch',
    description: 'Replace radio-based dispatch with a mobile app for field crews.',
    owner: 'Lina Hassan',
    currentProcess: 'Radio calls + paper work orders.',
    enhancedProcess: 'Mobile app with GPS routing, photo capture, and offline mode.',
    budget: '$640K',
    demandNumber: 'DEM-918',
    status: 'Active',
    urgency: 'Medium',
    comments: '',
    implementer: 'Internal',
    logDate: daysAgo(2),
    logDescription: 'Pilot with Sector 4 crews begins Monday.',
    severity: 'Low',
    updatedAt: daysAgo(2),
  },
  {
    id: 'INIT-1006',
    category: 'Securities',
    name: 'SOC 2 Readiness Uplift',
    description: 'Harden logging, access control, and incident response to achieve SOC 2 Type II.',
    owner: 'Marco Silva',
    currentProcess: 'Ad-hoc controls; inconsistent audit coverage.',
    enhancedProcess: 'Documented control set mapped to SOC 2 CC requirements, quarterly attestations.',
    budget: '$420K',
    demandNumber: 'DEM-920',
    status: 'Active',
    urgency: 'High',
    comments: 'External auditor engaged.',
    implementer: 'KPMG',
    logDate: daysAgo(1),
    logDescription: 'Gap analysis delivered. 17 findings — 4 high priority.',
    severity: 'High',
    updatedAt: daysAgo(1),
  },
  {
    id: 'INIT-1007',
    category: 'Product Replacements',
    name: 'Legacy SCADA Retirement',
    description: 'Retire the 1990s SCADA platform in favour of a modern EMS.',
    owner: 'Sarah Al-Mansoori',
    currentProcess: 'In-house SCADA with limited vendor support.',
    enhancedProcess: 'Vendor-managed EMS with modern protocol support and 24/7 SLA.',
    budget: '$8.6M',
    demandNumber: 'DEM-924',
    status: 'Delayed',
    urgency: 'High',
    comments: 'Vendor integration testing slipped 6 weeks.',
    implementer: 'Siemens',
    logDate: daysAgo(4),
    logDescription: 'Go-live rescheduled to next quarter. Board informed.',
    severity: 'High',
    updatedAt: daysAgo(4),
  },
  {
    id: 'INIT-1008',
    category: 'Infrastructure',
    name: 'Data Centre Cooling Retrofit',
    description: 'Replace legacy CRAC units with evaporative cooling for PUE improvement.',
    owner: 'David Okonkwo',
    currentProcess: 'Traditional compressor cooling — PUE 1.72.',
    enhancedProcess: 'Evaporative + free cooling — target PUE 1.32.',
    budget: '$3.2M',
    demandNumber: 'DEM-928',
    status: 'Pending',
    urgency: 'Low',
    comments: '',
    implementer: 'Johnson Controls',
    logDate: daysAgo(10),
    logDescription: 'RFP responses under evaluation.',
    severity: 'Low',
    updatedAt: daysAgo(10),
  },
  {
    id: 'INIT-1009',
    category: 'Others',
    name: 'Board Portfolio Transparency Page',
    description: 'Public-facing page summarising strategic initiative progress.',
    owner: 'Ahmed Karim',
    currentProcess: 'No public disclosure today.',
    enhancedProcess: 'Quarterly published page with KPIs and board commentary.',
    budget: '$90K',
    demandNumber: 'DEM-930',
    status: 'Active',
    urgency: 'Low',
    comments: '',
    implementer: 'Internal',
    logDate: daysAgo(7),
    logDescription: 'Draft page reviewed by comms. Awaiting board sign-off.',
    severity: 'Low',
    updatedAt: daysAgo(7),
  },
];

export const seedAuditLogs: AuditLog[] = seedInitiatives.map((i) => ({
  id: `log-seed-${i.id}`,
  initiativeId: i.id,
  initiativeName: i.name,
  logDate: i.logDate,
  logDescription: i.logDescription,
  logSeverity: i.severity,
  status: i.status,
  category: i.category,
}));

seedAuditLogs.push(
  {
    id: 'log-seed-extra-1',
    initiativeId: 'INIT-1001',
    initiativeName: 'Predictive Grid Demand Engine',
    logDate: daysAgo(0),
    logDescription: 'Model v2.1 calibration run completed. MAPE improved to 3.1%.',
    logSeverity: 'Low',
    status: 'Active',
    category: 'AIs',
  },
  {
    id: 'log-seed-extra-2',
    initiativeId: 'INIT-1006',
    initiativeName: 'SOC 2 Readiness Uplift',
    logDate: daysAgo(0),
    logDescription: 'Incident response drill — findings routed to security ops.',
    logSeverity: 'Medium',
    status: 'Active',
    category: 'Securities',
  },
  {
    id: 'log-seed-extra-3',
    initiativeId: 'INIT-1005',
    initiativeName: 'Field Ops Mobile Dispatch',
    logDate: daysAgo(6),
    logDescription: 'User acceptance testing session with 12 crew leads.',
    logSeverity: 'Low',
    status: 'Active',
    category: 'Services',
  },
);
